-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 20, 2025 at 10:53 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `travelwish`
--

-- --------------------------------------------------------

--
-- Table structure for table `beach`
--

CREATE TABLE `beach` (
  `beach_id` int(5) NOT NULL,
  `dest_name` varchar(150) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `tip1` varchar(150) NOT NULL,
  `tip2` varchar(150) NOT NULL,
  `tip3` varchar(150) NOT NULL,
  `tip4` varchar(150) NOT NULL,
  `best_time` varchar(150) NOT NULL,
  `fileImg` varchar(500) NOT NULL,
  `city` varchar(50) NOT NULL,
  `states` varchar(50) NOT NULL,
  `budget` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `blog`
--

CREATE TABLE `blog` (
  `blog_id` int(5) NOT NULL,
  `blog_title` varchar(150) NOT NULL,
  `content` varchar(1000) NOT NULL,
  `fileImg` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `destination`
--

CREATE TABLE `destination` (
  `place_id` int(5) NOT NULL,
  `dest_name` varchar(100) NOT NULL,
  `description` varchar(5000) NOT NULL,
  `tip1` varchar(150) NOT NULL,
  `tip2` varchar(150) NOT NULL,
  `tip3` varchar(150) NOT NULL,
  `tip4` varchar(150) NOT NULL,
  `best_time` varchar(150) NOT NULL,
  `fileImg` varchar(500) NOT NULL,
  `city` varchar(50) NOT NULL,
  `states` varchar(50) NOT NULL,
  `budget` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `destination`
--

INSERT INTO `destination` (`place_id`, `dest_name`, `description`, `tip1`, `tip2`, `tip3`, `tip4`, `best_time`, `fileImg`, `city`, `states`, `budget`) VALUES
(1, 'Mount Abu', 'sasdassad', 'asd', 'be secure', 'very cold', 'night cold', 'december to february', ' [\"6787d9836e853.jpg\",\"6787d9836eb93.jpeg\"]', 'mount abu', 'Rajasthan', 1000),
(3, 'Tirupati', 'Tirupati, located in the Chittoor district of Andhra Pradesh, is one of the most sacred pilgrimage destinations in India. Famous for the Tirumala Venkateswara Temple, this holy city attracts millions of devotees annually. Apart from its religious significance, Tirupati offers serene landscapes, waterfalls, and cultural heritage, making it an ideal blend of spirituality and natural beauty.', 'Book Darshan Tickets Early: Ensure you book your temple darshan tickets online through the TTD (Tirumala Tirupati Devasthanam) portal well in advance ', 'Dress Code: Wear traditional attire, as the temple has a strict dress code for devotees.', 'Explore Beyond the Temple: Visit places like Kapila Theertham, Sri Kalahasti, and Chandragiri Fort for a wholesome experience.', 'Stay Hydrated: The climb to Tirumala hills can be physically demanding, so keep yourself hydrated and carry light snacks.', 'The ideal time to visit Tirupati is September to March, when the weather is pleasant and the footfall is slightly lower than during major festivals.', '[\"67a3126137183.jpg\",\"67a3126137698.jpg\",\"67a31261378db.jpg\",\"67a3126137ab5.png\",\"67a3126137c8c.jpg\"]', 'Tirupati', 'Andhra Pradesh', 3000),
(4, 'Araku Valley', 'Nestled in the lush Eastern Ghats, Araku Valley is a pristine hill station in Andhra Pradesh, renowned for its breathtaking landscapes, coffee plantations, and tribal culture. A perfect getaway from city life, Araku boasts picturesque valleys, waterfalls, and caves. Its tranquil atmosphere and unspoiled natural beauty make it a must-visit destination for nature lovers and adventure enthusiasts.', 'Scenic Train Ride: Take the Visakhapatnam-Araku Valley train to enjoy the mesmerizing views of tunnels, bridges, and waterfalls.', 'Coffee Museum: Don’t miss the Araku Coffee Museum, where you can learn about the region’s world-famous coffee and indulge in a fresh brew.', 'Explore Local Tribes: Visit the Tribal Museum to gain insights into the traditions and lifestyle of indigenous communities.', 'Adventure Activities: Enjoy trekking, zip-lining, and camping amidst the serene hills for an adventurous experience.', 'October to March is the best time to visit Araku Valley, as the weather is cool and perfect for exploring its natural attractions.', '[\"67a313f290a0b.jpg\",\"67a313f290fde.jpg\",\"67a313f291628.jpg\",\"67a313f291943.jpg\",\"67a313f291c00.jpg\"]', 'Alluri Sitharama Raju district', 'Andhra Pradesh', 3000),
(5, 'Visakhapatnam', 'Visakhapatnam, affectionately called Vizag, is a bustling coastal city known for its pristine beaches, scenic hills, and vibrant cultural heritage. Situated along the Bay of Bengal, this city is a harmonious blend of natural beauty, modern urbanism, and historical significance. Key attractions like the Rama Krishna Beach, Kailasagiri, and INS Kurusura Submarine Museum make it a favorite among travelers. With its rich history and proximity to picturesque locations like Araku Valley, Vizag is perfect for a refreshing getaway.', 'Spend time at RK Beach, Yarada Beach, and Rushikonda Beach for stunning sunrises and water sports.', 'Museums and History: Visit the Submarine Museum and the Maritime Museum to dive into India’s naval history.', 'Local Delicacies: Don’t miss the seafood and Andhra specials like spicy prawns, fish curry, and bamboo chicken.', 'Day Trips: Plan visits to Simhachalam Temple, Borra Caves, and Araku Valley to explore Vizag’s surroundings.', 'The best time to visit Vizag is between October and February, when the weather is cool and perfect for beach outings and sightseeing.', '[\"67a3155717850.jpg\",\"67a3155717bf4.jpg\",\"67a3155717ed2.jpg\",\"67a315571814b.jpg\",\"67a3155718360.jpg\",\"67a31557185b3.jpg\"]', 'Visakhapatnam', 'Andhra Pradesh', 3000),
(6, 'Vijayawada', 'Vijayawada, the \"<b>Land of Victory</b>,\" is a vibrant city on the banks of the Krishna River. Known for its cultural heritage, ancient temples, and modern urban development, it is one of Andhra Pradesh\'s most bustling cities. Key attractions like the Kanaka Durga Temple, Prakasam Barrage, and Bhavani Island offer a mix of spirituality, natural beauty, and leisure activities. Vijayawada is also a prominent hub for shopping and delicious Andhra cuisine.', 'Temple Visits: Visit the Kanaka Durga Temple, a revered shrine situated atop Indrakeeladri Hill, for a spiritual experience.', 'Leisure Spots: Spend time at Bhavani Island for water sports, picnics, and serene views of the Krishna River.', 'Local Cuisine: Relish Andhra specialties like spicy biryani, pulihora, and Gongura dishes at local restaurants.', 'Transport: Utilize auto-rickshaws or rental cars to navigate the city easily.', 'The best time to visit Vijayawada is from October to March, as the weather is pleasant for exploring outdoor attractions.', '[\"67a316984ba36.jpg\",\"67a316984befb.jpeg\",\"67a316984c210.jpg\",\"67a316984c4f4.jpg\"]', 'NTR district', 'Andhra Pradesh', 2000),
(7, 'Anantapur', 'Anantapur, located in the Rayalaseema region of Andhra Pradesh, is known for its historical significance, temples, and beautiful landscapes. The city offers a peaceful ambiance and is home to attractions like the <b>Lepakshi Temple</b> and <b>Bhoga Nandeeshwara Temple</b>. Anantapur is also famous for its handloom industries, including the renowned <b>Madhavaram silk sarees</b>.', 'Visit <b>Lepakshi Temple</b> for historical and architectural wonders.', 'Explore the local handloom industries and buy silk sarees.', 'Don\'t miss a visit to Bhoga Nandeeshwara Temple.', 'Stay in local homestays for a cultural experience.', 'The best time to visit Anantapur is from October to March, as the weather is pleasant for exploring outdoor attractions.', '[\"67a3182577711.jpg\",\"67a3182577a69.jpg\",\"67a3182577d55.webp\"]', 'Anantapur', 'Andhra Pradesh', 2000),
(8, 'Puttaparthi', 'Puttaparthi is a small town in Andhra Pradesh famous for being the birthplace of spiritual leader <b>Sri Sathya Sai Baba</b>. Known for its spiritual significance, Puttaparthi attracts visitors seeking peace, serenity, and spiritual enrichment. Key attractions include <b>Prashanti Nilayam</b>, the spiritual headquarters of Sai Baba\'s followers, and the <b>Sai Kulwant Hall</b>.', 'Attend spiritual discourses and bhajans at <b>Prashanti Nilayam</b>.', 'Explore the spiritual teachings of <b>Sri Sathya Sai Baba</b>.', 'Participate in the seva activities organized by the trust.', 'Dress conservatively while visiting spiritual sites.', 'The best time to visit Puttaparthi is from October to March, as the weather is pleasant and ideal for spiritual retreats and exploring key attractions', '[\"67a8334f59689.jpg\",\"67a8334f59ea9.jpg\",\"67a8334f5a1f1.jpg\",\"67a8334f5a511.png\"]', 'Puttaparthi', 'Andhra Pradesh', 3000),
(9, 'Basilica of Bom Jesus', 'The Basilica of Bom Jesus, a UNESCO World Heritage Site, is a magnificent example of Baroque architecture and a prominent pilgrimage site in Goa. It houses the relics of St. Francis Xavier, attracting millions of visitors annually. The intricate carvings, stunning frescoes, and rich history make it a must-visit landmark.', 'Dress modestly as it is a religious site', 'Visit early morning to avoid crowds', ' Attend the Sunday mass for a spiritual experience.', 'Explore the nearby Se Cathedral and Church of St. Francis of Assisi.', 'The best time to visit the <b>Basilica of Bom Jesus</b> in Goa is from November to February, as the weather is cool and comfortable for exploring this', '[\"67a835b7b1f4e.jpg\",\"67a835b7b2349.jpg\",\"67a835b7b25ee.jpg\",\"67a835b7b27ca.jpg\",\"67a835b7b2997.jpg\",\"67a835b7b2b60.jpg\"]', 'Goa', 'Goa', 1500),
(10, 'Chapora Fort', 'Chapora Fort, famous for its appearance in Bollywood movies, offers a stunning panoramic view of the <b>Arabian Sea</b> and the surrounding beaches. This historic fort, built by the Portuguese, is a great spot to unwind and capture mesmerizing sunsets. It’s a favorite among history buffs and couples seeking romantic moments.', 'Wear comfortable shoes for climbing the fort', 'Visit early morning or late evening for the best views.', 'Bring a camera to capture scenic landscapes.', 'Avoid visiting during the afternoon to escape the heat.', 'The best time to visit Chapora Fort in Goa is from October to March, as the weather is pleasant for exploring the fort and enjoying stunning sunset vi', '[\"67a8378fb3117.png\",\"67a8378fb357f.jpg\",\"67a8378fb386f.jpg\"]', 'Bardez', 'Goa', 2000),
(11, 'Dudhsagar Falls', 'Dudhsagar Falls, one of India’s tallest waterfalls, is a breathtaking natural wonder located amidst the lush greenery of the Western Ghats. Its cascading white waters resemble a sea of milk, making it a visual spectacle. A trek through dense forests to reach the falls is an adventure in itself. It\'s a must-visit destination for nature and photography enthusiasts.', 'Wear sturdy shoes for the trek to the falls.', 'Visit during monsoons for the most stunning views.', 'Book a jeep safari for easy access to the falls.', 'Carry snacks and water for the journey.', 'The best time to visit Dudhsagar Falls is from June to October, as the monsoon season enhances the waterfall’s beauty, making it a breathtaking sight ', '[\"67a839692ba19.jpg\",\"67a839692bdc8.jpg\",\"67a839692c056.jpg\",\"67a839692c288.jpg\"]', 'South Goa', 'Goa', 2000),
(12, 'Baga Beach', 'Baga Beach is synonymous with electrifying nightlife, thrilling water sports, and beachside parties. Known for its buzzing clubs like Tito’s and Mambo’s, it\'s a hotspot for party-goers. During the day, you can relax on the soft sands or indulge in activities like banana boat rides and parasailing. Baga is the ultimate destination for fun and relaxation in Goa.', 'Visit in the evening to experience the nightlife.', 'Book water sports in advance for better deals.', 'Try fresh seafood at beachside cafes.', 'Explore the nearby Saturday Night Market.', 'The best time to visit Baga Beach in Goa is from November to January, as the weather is ideal for enjoying beachside parties, thrilling water sports, ', '[\"67a83ac6e4e2f.jpg\",\"67a83ac6e51b3.jpg\",\"67a83ac6e53a1.jpg\",\"67a83ac6e5570.jpg\",\"67a83ac6e5731.jpg\"]', 'Bardez', 'Goa', 4000),
(13, 'Panaji', 'Panaji, the capital city of Goa, is a delightful blend of Portuguese heritage and modern charm. With its colorful houses, cobblestone streets, and serene <b>Mandovi River</b>, Panaji offers a unique cultural experience. Attractions like the Immaculate Conception Church, <b>Fontainhas Latin Quarter</b>, and <b>Miramar Beach</b> add to its allure. It\'s a hub for food lovers and history buffs alike.', 'Take a heritage walk through the <b>Fontainhas area</b>.', 'Try traditional Goan dishes at local restaurants', 'Visit the casinos along the <b>Mandovi River</b> for entertainment.', 'Rent a bike to explore the city at your own pace', 'The best time to visit Panaji in Goa is from October to February, as the pleasant weather makes it ideal for exploring its Portuguese heritage, scenic', '[\"67a84703c909f.jpg\",\"67a84703c9476.jpg\",\"67a84703c9733.jpg\",\"67a84703c9a3d.jpg\",\"67a84703c9d40.jpg\",\"67a84703ca01a.jpg\",\"67a84703ca303.jpg\"]', 'Panaji', 'Goa', 3500),
(14, 'Anjuna Beach', 'Anjuna Beach is a paradise for hippies and party enthusiasts. Famous for its flea markets, trance parties, and rocky shoreline, this beach perfectly blends natural beauty and cultural vibes. It\'s an ideal place for backpackers and solo travelers seeking adventure, yoga retreats, and local crafts. The laid-back ambiance and mesmerizing sunsets make it unforgettable.', 'Explore the <b>Wednesday Flea Market</b> for unique souvenirs and handicrafts.', 'Attend a beach party to experience the vibrant nightlife.', 'Carry a camera for stunning sunset shots.', 'Visit the nearby Chapora Fort for a panoramic view of the Arabian Sea.', 'The best time to visit <b>Anjuna Beach</b> in Goa is from November to March, as the weather is perfect for enjoying beach parties, exploring the flea ', '[\"67a84c8047b5f.jpg\",\"67a84c8047ed5.jpg\",\"67a84c8048191.jpg\",\"67a84c804845d.jpg\",\"67a84c8048767.jpg\",\"67a84c8048a5d.jpg\"]', 'North Goa', 'Goa', 3000),
(15, 'Calangute Beach', '<b>Calangute Beach</b>, often referred to as the \"Queen of Beaches,\" is one of the most famous and vibrant tourist destinations in Goa. Known for its breathtaking golden sands, crystal-clear waters, and lively atmosphere, this beach attracts travelers from all over the world. Whether you\'re looking for a peaceful retreat by the shore or an adrenaline-filled adventure, <b>Calangute Beach</b> has something for everyone.  \r\n\r\nAdventure seekers can indulge in thrilling water sports such as parasailing, jet skiing, banana boat rides, and windsurfing, while those who prefer a more laid-back experience can relax under beach umbrellas and soak in the stunning coastal views. The beach is lined with numerous shacks and restaurants serving mouthwatering Goan delicacies, fresh seafood, and exotic drinks, making it a paradise for food lovers.  \r\n\r\nIn addition to its natural beauty, <b>Calangute Beach</b> is a hub for nightlife, shopping, and cultural experiences. From bustling flea markets selling ', 'Visit early morning for a peaceful experience before the crowds arrive.', 'Don’t miss the beach shacks for authentic Goan cuisine', 'Try water sports for an adrenaline rush.', 'Shop for souvenirs at the nearby Calangute Market.', 'The best time to visit Calangute Beach in Goa is from November to February, as the pleasant weather makes it ideal for enjoying water sports, beachsid', '[\"67a84f4d61044.jpg\",\"67a84f4d6165f.jpg\",\"67a84f4d61905.jpg\",\"67a84f4d61af0.jpg\",\"67a84f4d61d13.jpg\",\"67a84f4d61fc9.jpg\",\"67a84f4d6221d.jpg\"]', 'North Goa', 'Goa', 4000),
(16, 'Chitrakot Waterfalls ', '<b>Chitrakoot Falls</b>, famously known as the \"Niagara of India,\" is one of the most breathtaking waterfalls in the country, located on the picturesque <b>Indravati River</b> in Chhattisgarh. This majestic cascade is renowned for its sheer grandeur, spanning an impressive width of nearly 300 meters, making it the widest waterfall in India.  \r\n\r\nThe beauty of <b>Chitrakoot Falls</b> is at its peak during the monsoon season when the river swells, and the falls thunder down with incredible force, creating a mesmerizing spectacle of nature. The surrounding lush greenery, misty atmosphere, and roaring waters make it a paradise for nature lovers, adventure seekers, and photographers looking to capture its awe-inspiring charm.  \r\n\r\nBesides its natural allure, <b>Chitrakoot Falls</b> holds cultural and spiritual significance, with many local legends associated with it. Visitors can also explore nearby attractions such as caves, temples, and viewpoints that enhance the overall experience. Whet', 'Visit during the monsoon for the best experience.', 'Wear waterproof shoes and carry rain gear.', 'Avoid swimming due to strong currents.', 'Explore nearby caves for spiritual enrichment.', 'The best time to visit Chitrakoot Falls in Chhattisgarh is from October to February, as the weather is pleasant and ideal for witnessing the breathtak', '[\"67a85561baf98.jpg\",\"67a85561bb4ca.jpg\",\"67a85561bb999.jpg\",\"67a85561bbbec.jpg\",\"67a85561bbf5a.png\",\"67a85561bc1d5.jpg\",\"67a85561bc469.jpg\"]', 'Bastar District', 'Chhattisgarh', 4000),
(17, 'Khandagiri Caves', '<b>Khandagiri and Udayagiri Caves</b> in <b>Bhubaneswar, Odisha</b>, are a remarkable <b>historic cluster of rock-cut caves</b> that date back to the 2nd century BCE. These ancient caves were carved by <b>Jain monks</b> during the reign of King Kharavela of the Mahameghavahana dynasty and serve as an important site for Jain heritage and Indian history. The caves are famous for their <b>intricate sculptures, inscriptions, and carvings</b> that depict scenes of royal processions, religious ceremonies, and daily life in ancient India.\r\n\r\nLocated on two adjacent hills, <b>Khandagiri and Udayagiri</b> offer breathtaking views of the city and its lush surroundings. Udayagiri, meaning \"Sunrise Hill,\" consists of 18 caves, including the famous <b>Rani Gumpha (Queen’s Cave)</b>, which is adorned with beautiful carvings and elaborate relief sculptures. Khandagiri, on the other hand, has 15 caves and features Jain temples and meditation spots that still attract devotees and tourists.\r\n\r\nVisitors can enjoy a peaceful and spiritual experience while exploring these caves, which are also known for their <b>archaeological and architectural significance</b>. The site is a perfect blend of <b>history, religion, and nature</b>, making it an ideal destination for history enthusiasts, photographers, and spiritual seekers. If you\'re in or around <b>Bhubaneswar</b>, don’t miss the chance to witness one of India’s finest examples of ancient rock-cut architecture.\r\n\r\nPlan your visit to <b>Khandagiri and Udayagiri Caves</b> today and immerse yourself in the rich cultural heritage of Odisha!', 'Best visited in the morning.', 'Combine with Udayagiri Caves for a complete tour.', 'Perfect for history and architecture lovers.', 'Photography is allowed but without flash.', 'October to February offers the best weather for visiting the caves and experiencing their historical significance.', '[\"67aefd513061a.jpg\",\"67aefd5130a24.jpg\",\"67aefd5130c86.jpg\",\"67aefd5130e94.jpg\",\"67aefd51311bc.jpg\",\"67aefd5131589.jpg\"]', 'Bhubaneswar', 'Odisha', 3000),
(18, 'Udaigiri Caves', '<b>Udayagiri Caves in Odisha</b> are one of India\'s most significant ancient rock-cut caves, showcasing the rich heritage of <b>Jainism</b> and intricate carvings that date back to the <b>2nd century BCE</b>. Located near <b>Bhubaneswar</b>, these caves were carved during the reign of King Kharavela and served as residential retreats for <b>Jain monks</b>. The site features beautifully sculpted pillars, detailed inscriptions, and religious motifs that provide a glimpse into the spiritual and cultural practices of ancient India.\r\n\r\nThe most famous cave, <b>Rani Gumpha (Queen’s Cave)</b>, is a two-story structure adorned with elaborate carvings and decorative elements. Other notable caves include <b>Hathi Gumpha</b>, known for its historical inscriptions, and <b>Ganesh Gumpha</b>, which features carvings of Jain deities. These caves not only reflect <b>architectural brilliance</b> but also serve as an important pilgrimage site for followers of Jainism.\r\n\r\nVisitors to <b>Udayagiri</b> can enjoy the serene ambiance, explore the <b>ancient sculptures</b>, and experience breathtaking views from the hilltop. Whether you\'re a history enthusiast, a spiritual seeker, or a traveler looking for <b>offbeat destinations in Odisha</b>, these caves offer an unforgettable journey into India\'s past.\r\n\r\nPlan your visit to <b>Udayagiri Caves in Odisha</b> and witness the timeless beauty of India’s ancient heritage!', 'Hire a guide for historical insights.', 'Visit alongside Khandagiri Caves.', 'Perfect spot for archaeology lovers.', 'Wear comfortable shoes for climbing.', 'The best time to visit Udayagiri Caves, Odisha, is October to March, when the weather is cool and pleasant for exploration. Avoid summer (April–June) ', '[\"67aefe0c16d11.jpg\",\"67aefe0c171c6.jpg\",\"67aefe0c17630.jpg\",\"67aefe0c1795e.jpg\"]', 'Bhubaneswar', 'Odisha', 3000),
(19, 'Dhauli Hill', '<b>Dhauli Hill in Odisha</b> is a historically significant <b>Buddhist site</b> where <b>Emperor Ashoka</b> embraced <b>Buddhism</b> after witnessing the devastation of the <b>Kalinga War</b> in the 3rd century BCE. Located just a few kilometers from <b>Bhubaneswar</b>, this sacred site is home to the famous <b>Shanti Stupa (Peace Pagoda)</b>, built to symbolize peace and non-violence. The white-domed stupa, constructed by the <b>Kalinga Nippon Buddha Sangha</b> and the <b>Japanese Buddhist community</b>, stands as a beacon of spiritual transformation and harmony.\r\n\r\nDhauli is also known for its <b>Ashokan Rock Edicts</b>, which are inscriptions carved on rock surfaces that reflect Ashoka’s commitment to <b>Dhamma (righteousness)</b> and his efforts to spread Buddhist teachings across India. These edicts, written in ancient Brahmi script, are among the earliest records of Buddhist philosophy and governance.\r\n\r\nSurrounded by lush greenery and overlooking the <b>Daya River</b>, where the battle of Kalinga was fought, Dhauli Hill offers a serene and meditative atmosphere. Visitors can explore the ancient rock-cut caves, visit Buddhist monasteries, and enjoy the breathtaking views from the hilltop.\r\n\r\nFor history enthusiasts, spiritual seekers, and travelers exploring <b>Odisha’s cultural heritage</b>, <b>Dhauli Hill</b> is a must-visit destination that tells the story of one of the greatest transformations in history. Plan your trip to this peaceful and historically rich site to experience the legacy of <b>Emperor Ashoka</b> and the timeless teachings of <b>Buddhism</b>.', 'Visit the Peace Pagoda for scenic views.', 'Read Ashokan inscriptions at the rock edicts.', 'Best visited during sunrise or sunset.', 'Ideal for history lovers.', 'October to March is great for visiting the Buddhist site with pleasant weather and scenic views.', '[\"67af00373795c.jpg\",\"67af003737c75.jpg\",\"67af003737e33.jpg\",\"67af003737fbb.jpg\",\"67af003738126.jpg\",\"67af0037382af.jpg\"]', 'Bhubaneswar', 'Odisha', 3000),
(20, 'Lingaraj Temple', '<b>Lingaraj Temple in Odisha</b> is a magnificent <b>11th-century Hindu temple</b> dedicated to <b>Lord Shiva</b> and is one of the finest examples of Kalinga-style architecture. Located in the heart of <b>Bhubaneswar</b>, this temple is not only a spiritual landmark but also an architectural masterpiece that attracts thousands of devotees and tourists every year. The towering <b>150-foot-high shikhara (spire)</b> dominates the city’s skyline, showcasing intricate carvings, sculptures, and detailed inscriptions that reflect the grandeur of ancient Indian craftsmanship.\r\n\r\nThe temple complex consists of <b>over 50 smaller shrines</b>, each dedicated to different Hindu deities, creating a divine and sacred atmosphere. The main deity, <b>Harihara</b>, is worshiped here as a combined form of <b>Lord Shiva and Lord Vishnu</b>, making it a unique spiritual destination for devotees of both traditions. The temple is surrounded by the holy <b>Bindusagar Lake</b>, where pilgrims take a ritual dip before offering prayers.\r\n\r\nOne of the best times to visit is during the grand festival of <b>Mahashivaratri</b>, when the temple is beautifully decorated, and thousands of devotees gather to seek blessings. As one of the oldest and most revered temples in <b>Bhubaneswar, the \"Temple City of India,\"</b> Lingaraj Temple is a must-visit for anyone exploring Odisha’s rich cultural and religious heritage.\r\n\r\nWhether you are a devotee, a history enthusiast, or an architecture lover, <b>Lingaraj Temple</b> offers an unforgettable experience of spirituality, history, and stunning craftsmanship. Plan your visit to this sacred site and witness the beauty of <b>Odisha’s architectural marvels</b>.', 'Morning visit is best for a peaceful darshan.', 'Explore the nearby Bindu Sagar Lake.', 'Non-Hindus can admire from outside.', 'Don\'t miss the annual Shivaratri festival.', 'October to March offers ideal weather for temple visits and historical exploration.', '[\"67af00ba54f18.jpg\",\"67af00ba5585a.jpg\",\"67af00ba561f0.jpg\",\"67af00ba5654e.jpg\",\"67af00ba567b4.jpg\",\"67af00ba56983.jpg\"]', 'Bhubaneswar', 'Odisha', 3500),
(21, 'Jagannath Temple', '<b>Jagannath Temple in Odisha</b> is one of the most sacred <b>Hindu pilgrimage sites</b> and a key destination in the revered Char Dham Yatra. Located in Puri, this ancient temple is dedicated to Lord Jagannath, a divine form of <b>Lord Vishnu</b>. Built in the <b>12th century</b> by King Anantavarman Chodaganga Deva, the temple is an architectural masterpiece of <b>Kalinga-style architecture</b>, with a towering <b>214-foot-high shikhara (spire)</b> that dominates Puri’s skyline.\r\n\r\nThe temple is world-famous for its grand annual festival, the <b>Rath Yatra</b>, where the deities—<b>Lord Jagannath, Balabhadra, and Subhadra</b>—are carried in massive, ornately decorated chariots. This spectacular event attracts millions of devotees from across India and beyond, making it one of the most celebrated religious festivals in the world.\r\n\r\nOne of the most unique aspects of <b>Jagannath Temple</b> is its <b>Mahaprasad</b>, a sacred offering cooked in the world’s largest kitchen. Prepared using age-old traditional methods, this divine food is considered to be directly blessed by <b>Lord Jagannath</b> and is shared among thousands of devotees every day.\r\n\r\nThe temple follows strict rituals and traditions that have been preserved for centuries, adding to its spiritual significance. While entry to the inner sanctum is restricted to Hindus, visitors can still admire the temple’s majestic architecture and experience the divine aura of the surroundings.\r\n\r\nA visit to <b>Puri Jagannath Temple</b> is an unforgettable spiritual journey, offering a glimpse into the rich cultural and religious heritage of <b>Odisha</b>. Whether you seek divine blessings, wish to witness the grandeur of the <b>Rath Yatra</b>, or explore India’s ancient temple architecture, this sacred site is a must-visit destination.', 'Non-Hindus are not allowed inside.', 'Visit early morning to avoid crowds.', 'Don\'t miss the Mahaprasad, temple food.', 'Respect temple etiquette and dress modestly.', 'July for the Rath Yatra festival, or October to February for comfortable weather and spiritual visits.', '[\"67af01736b8fa.jpg\",\"67af01736bc2c.jpg\",\"67af01736be2c.jpg\",\"67af01736c026.jpg\",\"67af01736c396.jpg\"]', 'Puri', 'Odisha', 3999),
(22, 'Chilika Lake', 'Chilika Lake in Odisha is Asia’s largest coastal lagoon, renowned for its migratory birds, dolphin spotting, and scenic boat rides. Spanning over 1,100 square kilometers, this breathtaking lagoon stretches across the districts of Puri, Khurda, and Ganjam. It serves as a vital habitat for rare and exotic bird species, including flamingos, pelicans, and herons, making it a paradise for birdwatchers and wildlife enthusiasts. The lake is also home to the endangered Irrawaddy dolphins, often seen near Satapada, making it a unique attraction for nature lovers.\r\n\r\n<p>A boat ride through the tranquil waters offers spectacular views of the surrounding landscape and a chance to explore <b>scenic islands like Kalijai Island and Honeymoon Island</b>. Recognized as a <b>Ramsar Wetland</b> site, <b>Chilika Lake</b> plays a crucial role in maintaining ecological balance and supports thousands of local fishermen.</p> <p>The lake’s <b>rich biodiversity</b> and cultural heritage make it one of Odisha’s top <b>eco-tourism destinations</b>. Plan your visit to <b>Chilika Lake</b> and experience its mesmerizing beauty, diverse wildlife, and serene boat rides that promise an unforgettable journey into nature’s lap.</p>', 'Visit in winter for birdwatching.', 'Take a boat ride to spot Irrawaddy dolphins.', 'Stay in eco-resorts for a serene experience.', 'Try fresh seafood from local vendors.', 'November to February is the best time for birdwatching and boating, with migratory birds arriving in the lake.', '[\"67af54dc56cf9.jpg\",\"67af54dc57894.jpg\",\"67af54dc57d82.jpg\",\"67af54dc58179.jpg\",\"67af54dc584e8.jpg\",\"67af54dc5886c.png\",\"67af54dc58c0b.jpg\"]', 'Puri', 'Odisha', 4000),
(23, 'Konark', '<b>Konark in Odisha</b> is home to the iconic <b>Sun Temple</b>, a UNESCO World Heritage Site and one of the greatest architectural wonders of India. Built in the <b>13th century</b> by King <b>Narasimha Deva I</b> of the Eastern Ganga Dynasty, this masterpiece is designed in the shape of a colossal <b>chariot</b> dedicated to <b>Surya, the Sun God</b>. The temple\'s intricate carvings, massive <b>chariot wheels</b>, and elaborate sculptures showcase the brilliance of ancient <b>Kalinga-style architecture</b>.\r\n\r\nThe temple complex features <b>24 intricately carved wheels</b>, each representing the hours of a day, along with detailed depictions of celestial beings, dancers, warriors, and mythological scenes. The precision and craftsmanship of these sculptures highlight the artistic excellence of medieval Odisha. Although parts of the main structure have been lost over time, the remaining ruins continue to mesmerize visitors with their grandeur.\r\n\r\nKonark is not just about historical architecture; it is also known for its vibrant cultural heritage. Every year, the town hosts the world-famous <b>Konark Dance Festival</b>, where classical dancers from across India perform against the backdrop of this ancient marvel. The nearby <b>Chandrabhaga Beach</b> adds to the scenic beauty, making it a perfect destination for history enthusiasts, photographers, and spiritual travelers.\r\n\r\nA visit to <b>Konark Sun Temple</b> is a journey into India\'s glorious past, where history, spirituality, and art come together in an awe-inspiring setting. Plan your trip to this legendary site and witness the timeless beauty of <b>Odisha’s architectural marvel</b>.', 'Visit during sunrise for the best views.', 'Carry water as the site requires walking.', 'Hire a guide for historical insights.', 'Combine with a trip to Chandrabhaga Beach.', 'November to February is perfect for exploring the Sun Temple and enjoying the Konark Dance Festival.', '[\"67af55edb608c.jpg\",\"67af55edb660f.jpg\",\"67af55edb6904.jpg\",\"67af55edb6d78.jpg\",\"67af55edb7111.jpg\",\"67af55edb73e4.jpg\",\"67af55edb763f.jpg\",\"67af55edb7882.jpg\"]', 'Puri', 'Odisha', 3500),
(24, 'Puri', 'Puri in Odisha is a renowned spiritual and scenic destination, attracting millions of pilgrims and tourists every year. Known for its rich cultural heritage, this coastal city is home to the iconic Jagannath Temple, one of the four sacred Char Dham pilgrimage sites. The city’s serene beaches, vibrant festivals, and deep-rooted traditions make it a must-visit destination for travelers seeking both religious significance and natural beauty.\r\n\r\n<p>The <b>Jagannath Temple</b> stands as the heart of Puri, famous for its annual <b>Rath Yatra</b>, where colossal chariots carry Lord Jagannath, Balabhadra, and Subhadra through the streets. This grand event attracts devotees and tourists from across the world. The temple’s history, architecture, and spiritual aura make it an unforgettable experience.</p> <p>Besides its religious charm, Puri is also known for its <b>golden sandy beaches</b>, especially <b>Puri Beach</b>, where visitors can relax, enjoy mesmerizing sunrises, and witness the vibrant local culture. The nearby <b>Chilika Lake</b>, a haven for migratory birds and dolphins, adds to the city\'s allure, making it a perfect blend of spirituality and nature.</p> <p>With its divine atmosphere, scenic beauty, and cultural richness, Puri is a destination that offers a unique experience for both pilgrims and nature lovers. Whether you seek blessings at the temple or a peaceful retreat by the sea, Puri welcomes you with open arms.</p>', 'Attend the Rath Yatra festival.', 'Enjoy sunrise at Puri Beach.', 'Try fresh seafood at local stalls.', 'Stay in beachfront resorts for the best experience.', 'October to February is the best time for beach visits, temple tours, and the famous Rath Yatra festival.', '[\"67af593346a20.jpeg\",\"67af59334780a.jpg\",\"67af593347b9f.jpg\",\"67af593347e1d.jpg\",\"67af593348086.jpg\",\"67af59334858b.jpg\",\"67af59334898f.jpg\",\"67af593348d80.jpg\",\"67af5933491be.png\"]', 'Puri', 'Odisha', 3500),
(25, 'Bhubaneswar', 'Bhubaneswar, the capital of Odisha, is a city steeped in history and culture, often referred to as the <b>Temple City of India.</b> This vibrant metropolis beautifully blends ancient heritage with modern development, making it one of India\'s most fascinating destinations. Home to centuries-old temples, bustling markets, and historical landmarks, Bhubaneswar is a paradise for history enthusiasts, spiritual seekers, and travelers exploring Odisha’s rich cultural tapestry.\r\n\r\n<p>The city’s most iconic landmark is the <b>Lingaraj Temple</b>, an architectural marvel dedicated to Lord Shiva, showcasing the exquisite <b>Kalinga-style architecture</b>. This 11th-century temple stands as a testament to Odisha’s deep spiritual roots and attracts thousands of devotees throughout the year.</p> <p>Beyond its temples, Bhubaneswar offers a wealth of attractions, including the <b>Udayagiri and Khandagiri Caves</b>, ancient Jain rock-cut caves with intricate carvings and historical significance. The city is also home to the <b>Mukteshwar Temple</b>, famous for its elegant torana (arched gateway), and the <b>Rajarani Temple</b>, known for its detailed sculptures and artistic beauty.</p> <p>As a rapidly growing urban hub, Bhubaneswar seamlessly blends tradition with modernity, featuring IT parks, vibrant markets, and lush parks like <b>Ekamra Kanan</b>. Whether you\'re exploring its historical wonders, savoring authentic Odia cuisine, or experiencing its bustling local life, Bhubaneswar offers an enriching journey into Odisha’s heart and soul.</p>', 'Visit the Lingaraj Temple early morning.', 'Explore the Khandagiri and Udayagiri caves.', 'Try local Odia cuisine.', 'Use public transport for easy travel.', 'October to February offers pleasant weather, making temple visits and city exploration comfortable.', '[\"67af5d9e831b1.jpg\",\"67af5d9e83745.jpg\",\"67af5d9e83b36.jpg\",\"67af5d9e83e5a.jpg\",\"67af5d9e84462.jpg\",\"67af5d9e84873.jpg\",\"67af5d9e84c3e.jpg\",\"67af5d9e84ed7.jpg\",\"67af5d9e8538d.jpg\",\"67af5d9e858da.jpg\",\"67af5d9e85d2e.jpg\",\"67af5d9e86121.jpg\"]', 'Bhubaneswar', 'Odisha', 4000),
(26, 'Nagaland War Cemetery', 'Nagaland War Cemetery is a solemn and historic site that stands as a tribute to the brave soldiers who fought in the Battle of Kohima during World War II. Located in the heart of Kohima, this beautifully maintained cemetery is a place of remembrance and reflection, honoring the sacrifices made by Allied forces in one of the fiercest battles fought on Indian soil. Surrounded by lush green hills, the cemetery offers a peaceful environment where visitors can pay their respects and learn about this significant chapter of history.\r\n\r\n<p>The <b>Nagaland War Cemetery</b> is the final resting place for over 1,400 soldiers who lost their lives in the battle against Japanese forces in 1944. Managed by the <b>Commonwealth War Graves Commission</b>, the cemetery features well-preserved gravestones, each inscribed with the names and regiments of the fallen heroes.</p> <p>One of the most striking elements of the cemetery is the famous <b>Kohima Epitaph</b>, which reads: “When You Go Home, Tell Them of Us and Say, For Your Tomorrow, We Gave Our Today.” This heartfelt tribute deeply resonates with visitors, reminding them of the courage and sacrifice of those who fought for freedom.</p> <p>Surrounded by scenic views, the <b>Nagaland War Cemetery</b> is not just a memorial but also a historical landmark that attracts history enthusiasts, researchers, and tourists alike. A visit to this site provides a poignant insight into Nagaland’s role in World War II and ensures that the legacy of these brave soldiers is never forgotten.</p>', 'Visit early morning for a peaceful experience.', 'Read the inscriptions for historical insights.', 'Photography is allowed but be respectful.', 'Pair your visit with the nearby museums.', 'October to March has mild temperatures, making it ideal for historical exploration.', '[\"67af5f862e1a0.jpeg\",\"67af5f862e534.jpeg\",\"67af5f862e76e.jpeg\",\"67af5f862e9fa.jpeg\"]', 'Kohima', 'Nagaland', 3000),
(27, 'Japfu Peak', 'Japfu Peak, the second-highest peak in Nagaland, is a breathtaking destination that offers an unparalleled experience for trekkers, nature enthusiasts, and adventure seekers. Rising to an elevation of approximately 3,048 meters, it provides a panoramic view of Nagaland’s rolling hills, dense forests, and mist-covered valleys. Located near Kohima, this peak is a must-visit for anyone looking to immerse themselves in the pristine beauty of the Northeast.\r\n\r\n<p>One of the most extraordinary features of <b>Japfu Peak</b> is the <b>world’s tallest rhododendron tree</b>, which soars over 100 feet high. Every spring, the tree bursts into a vibrant display of red and pink blossoms, creating a mesmerizing sight. This rare natural wonder has earned Japfu Peak global recognition and attracts botanists and nature lovers from around the world.</p> <p>The trek to <b>Japfu Peak</b> is a rewarding challenge, taking adventurers through scenic trails, dense bamboo forests, and high-altitude meadows. As trekkers ascend, they encounter breathtaking landscapes, crystal-clear streams, and diverse flora and fauna unique to this region. The sunrise from the peak is an unforgettable spectacle, painting the sky in golden hues and offering a view that stretches as far as the eye can see.</p> <p>For wildlife enthusiasts, the region around Japfu Peak is home to rare species of birds and animals, making it an excellent spot for birdwatching and photography. The untouched beauty of this area, combined with its peaceful surroundings, makes it an ideal getaway for those seeking solitude and a deep connection with nature.</p> <p>Whether you’re an experienced trekker or a first-time explorer, <b>Japfu Peak</b> promises an adventure like no other. Its mix of natural beauty, rare flora, and scenic trekking trails make it one of Nagaland’s most remarkable attractions. A journey to Japfu Peak is not just a trek—it’s an experience that stays with you forever.</p>', 'Trek early morning for the best views.', 'Carry sufficient water and energy snacks.', 'Wear trekking shoes for safety.', 'Ideal for adventure seekers.', 'October to March is perfect for trekking with clear skies and moderate temperatures.', '[\"67af638ba9ec1.jpg\",\"67af638baa4d3.jpg\",\"67af638baa94c.jpg\"]', 'Kohima', 'Nagaland', 3500),
(28, 'Kisama Heritage Village', 'Kisama Heritage Village is the cultural heart of Nagaland, serving as the main venue for the world-famous Hornbill Festival. Located just 12 km from Kohima, this heritage village is a living museum that showcases the vibrant traditions, customs, and lifestyle of Nagaland’s diverse tribal communities. Designed to preserve and promote the rich heritage of the Naga people, Kisama offers visitors an immersive experience into the region’s history, art, and indigenous practices.\r\n\r\n<p>The highlight of <b>Kisama Heritage Village</b> is the annual <b>Hornbill Festival</b>, held every December. Often referred to as the \"Festival of Festivals,\" this grand event brings together all the major Naga tribes, featuring traditional music, folk dances, indigenous sports, and craft exhibitions. The festival is a colorful spectacle where visitors can witness warrior performances, taste authentic Naga cuisine, and explore handcrafted tribal artifacts.</p> <p>The village itself is a fascinating attraction, with its <b>morungs</b> (traditional Naga huts), each representing different Naga tribes. These morungs display unique architectural styles and serve as cultural hubs where visitors can learn about tribal traditions, storytelling, and ancestral customs. The <b>World War II Museum</b> within Kisama offers a glimpse into Nagaland’s wartime history, showcasing artifacts, photographs, and documents from the Battle of Kohima.</p> <p>Beyond the festival, <b>Kisama Heritage Village</b> remains an essential destination for cultural tourism in Nagaland. Visitors can explore its open-air amphitheater, browse local handicraft stalls, and interact with artisans preserving centuries-old traditions. Whether you visit during the Hornbill Festival or any other time of the year, Kisama offers an authentic insight into Nagaland’s rich cultural legacy.</p> <p>A trip to <b>Kisama Heritage Village</b> is more than just a sightseeing experience—it’s a deep dive into the soul of Naga heritage. Whether you\'re a culture enthusiast, history buff, or adventure traveler, this remarkable destination guarantees an unforgettable journey through the traditions of Nagaland.</p>', 'Visit in December for the Hornbill Festival.', 'Try the local rice beer.', 'Interact with local tribes for a deeper understanding.', 'Photography enthusiasts will love this place.', 'December is ideal to witness the Hornbill Festival, a grand celebration of Naga culture and traditions.', '[\"67af64e7ee5ee.jpg\",\"67af64e7eebe6.jpg\",\"67af64e7ef22a.jpg\",\"67af64e7ef8da.jpg\"]', 'Kohima', 'Nagaland', 3500),
(29, 'Dzukou Valley', 'Dzukou Valley, often referred to as the \"Valley of Flowers of the Northeast,\" is a breathtaking paradise nestled on the border of Nagaland and Manipur. Famous for its rolling green meadows, seasonal wildflowers, and serene landscapes, this pristine valley sits at an altitude of 2,452 meters, offering a perfect escape for trekkers, nature lovers, and adventure seekers. Its untouched beauty and cool climate make it one of the most sought-after trekking destinations in Northeast India.\r\n\r\n<p>The most enchanting feature of <b>Dzukou Valley</b> is its lush greenery, which transforms into a colorful carpet of blooming flowers during the monsoon season. The valley is home to the rare and exquisite <b>Dzukou Lily</b>, a unique flower that grows only in this region. The landscape is dotted with a variety of wildflowers, shrubs, and dwarf bamboo, giving it a surreal charm that captivates every visitor.</p> <p>The <b>Dzukou Valley trek</b> is a moderately challenging yet rewarding experience. Trekkers can embark on the journey from <b>Viswema</b> or <b>Zakhama</b>, with the Viswema route being the more popular and accessible option. The trail takes adventurers through dense forests, rugged terrains, and scenic ridges, eventually leading to the breathtaking valley. Once at the top, the panoramic view of the emerald-green valley stretching as far as the eye can see is truly mesmerizing.</p> <p>Besides trekking, visitors can explore the valley’s numerous caves and crystal-clear streams, making it a perfect spot for camping and photography. The valley remains untouched by commercial tourism, preserving its tranquil and unspoiled charm. The peaceful surroundings and cool mountain breeze make <b>Dzukou Valley</b> an ideal getaway for those seeking solitude and a deep connection with nature.</p> <p>Whether you\'re an adventure enthusiast, a photographer, or simply someone who loves the beauty of the great outdoors, <b>Dzukou Valley</b> promises an unforgettable experience. A trek to this hidden gem of Nagaland is more than just a journey—it\'s a chance to witness one of India\'s most stunning natural wonders.</p>', 'Carry warm clothes as it gets cold at night.', 'Dzukou Valley is a beautiful valley in Nagaland', 'Trekking is moderate, so wear comfortable shoes.', 'Camping is a great option here.', 'Best visited from June to September when the valley blooms with colorful flowers, creating a breathtaking landscape.', '[\"67af677b6c1de.jpg\",\"67af677b6c6da.jpg\"]', 'Viswema', 'Nagaland', 3000),
(30, 'Kohima', 'Kohima, the capital city of Nagaland, is a fascinating blend of history, culture, and breathtaking landscapes. Perched at an altitude of 1,444 meters, this picturesque city is surrounded by lush green hills, making it one of the most beautiful capitals in Northeast India. Known for its rich Naga heritage, historic landmarks, and vibrant festivals, Kohima is a must-visit destination for travelers seeking an authentic cultural experience.\r\n\r\n<p>One of the most iconic events in <b>Kohima</b> is the world-famous <b>Hornbill Festival</b>, held every December at Kisama Heritage Village. Dubbed the \"Festival of Festivals,\" this grand celebration showcases the diverse traditions, music, dance, and crafts of Nagaland’s many tribes. It is a spectacular opportunity to witness Naga warrior dances, enjoy indigenous sports, and savor traditional Naga cuisine.</p> <p>History enthusiasts will find <b>Kohima War Cemetery</b> a deeply moving site. This memorial honors the soldiers who fought in the historic <b>Battle of Kohima</b> during World War II, a crucial turning point in the Burma Campaign. The cemetery, maintained by the Commonwealth War Graves Commission, offers a peaceful yet solemn atmosphere, with engraved tombstones paying tribute to the fallen heroes.</p> <p>Nature lovers can explore the stunning <b>Dzukou Valley</b>, located just outside Kohima. Famous for its rolling green hills, seasonal wildflowers, and serene trekking trails, this valley is often called the \"Valley of Flowers of the Northeast.\" It is a paradise for hikers, photographers, and anyone seeking an escape into nature.</p> <p>Kohima is also home to the <b>State Museum</b>, which offers insights into the history, traditions, and artifacts of Nagaland’s various tribes. Visitors can explore displays of traditional tribal attire, weapons, jewelry, and ancient relics, providing a deeper understanding of Naga culture.</p> <p>With its mix of <b>cultural richness, historical significance, and natural beauty</b>, Kohima is a destination that appeals to history buffs, adventure seekers, and culture enthusiasts alike. Whether you\'re attending the Hornbill Festival, exploring war memorials, or trekking through breathtaking valleys, Kohima promises an unforgettable experience in the heart of Nagaland.</p>', 'Visit during the Hornbill Festival for a cultural experience.', 'Explore local Naga cuisine.', 'Visit the Kohima War Cemetery.', 'Plan a trek to nearby hills.', 'Winter months (October to March) offer pleasant weather, perfect for sightseeing and experiencing the Hornbill Festival.', '[\"67af69721b99d.jpg\",\"67af69721bc82.jpg\",\"67af69721bf50.jpeg\",\"67af69721c2f9.jpg\",\"67af69721c604.jpeg\",\"67af69721c88e.jpg\",\"67af69721cb69.jpg\",\"67af69721d3d2.jpeg\"]', 'Kohima', 'Nagaland', 3500),
(31, 'Durtlang Hills', 'Durtlang Hills, located on the northern edge of Aizawl, Mizoram, offer a breathtaking vantage point to admire the city’s panoramic beauty. These hills are a paradise for nature lovers, adventure seekers, and photographers, providing a serene escape from the bustling city life. With their lush greenery, cool breeze, and stunning sunrise and sunset views, Durtlang Hills have become a must-visit destination in Mizoram.\r\n\r\n<p>One of the main attractions of <b>Durtlang Hills</b> is the <b>trekking trails</b> that lead to the highest points, offering an adrenaline-filled adventure for hiking enthusiasts. The trails take visitors through dense forests, rugged terrains, and scenic landscapes, making the trek both challenging and rewarding. Once at the top, visitors are greeted with a mesmerizing view of <b>Aizawl</b>, with its houses clinging to the hillsides and the distant mountains creating a stunning backdrop.</p> <p>For those who prefer a more relaxed experience, <b>Durtlang Hills</b> also provide several peaceful spots to sit and soak in the beauty of Mizoram’s capital. The hills are a great place for picnics, meditation, or simply enjoying nature’s tranquility away from the urban hustle. The refreshing mountain air and the soothing sounds of chirping birds make it a perfect retreat.</p> <p>Besides the natural beauty, the hills are also home to the **Durtlang Presbyterian Hospital**, a historical institution known for its contribution to healthcare in Mizoram. Visitors can also explore nearby cultural sites to get a deeper understanding of Mizo heritage and traditions.</p> <p>Whether you\'re an adventure lover looking for a thrilling hike, a photographer searching for the perfect landscape shot, or a traveler seeking a peaceful retreat, <b>Durtlang Hills</b> offer an unforgettable experience. Their combination of **stunning viewpoints, thrilling trekking paths, and serene atmosphere** makes them one of Mizoram’s top attractions.</p>\"', 'Take a short trek to enjoy the natural beauty.', 'Take your camera for stunning landscape shots.', 'Go for an early morning trek for a peaceful experience.', 'Enjoy a bird’s eye view of Aizawl from the top.', 'October to March - Clear views and comfortable weather.', '[\"67b14db0d9b84.jpg\",\"67b14db0da48c.jpg\",\"67b14db0da873.jpg\",\"67b14db0dac05.jpg\",\"67b14db0daf8b.jpg\",\"67b14db0db1dc.jpg\"]', 'Aizawl', 'Mizoram', 6000);
INSERT INTO `destination` (`place_id`, `dest_name`, `description`, `tip1`, `tip2`, `tip3`, `tip4`, `best_time`, `fileImg`, `city`, `states`, `budget`) VALUES
(32, 'Reiek', 'Reiek, one of Mizoram\'s most popular trekking destinations, offers breathtaking panoramic views of lush green hills and deep valleys. Located just 29 km from Aizawl, this scenic hill is a paradise for nature lovers, adventure seekers, and cultural enthusiasts. Standing at an altitude of approximately 1,546 meters (5,072 feet), Reiek provides a stunning bird’s-eye view of the surrounding landscapes, making it a must-visit attraction in Mizoram.\r\n\r\n<p>The <b>trek to Reiek</b> is a rewarding experience, taking visitors through dense forests, rocky trails, and misty pathways. The journey is filled with serene beauty, chirping birds, and the fresh mountain air, making it an unforgettable adventure. Once at the summit, trekkers are greeted with breathtaking views of the <b>Mizo hills</b>, with distant glimpses of the plains of Bangladesh on a clear day.</p> <p>Beyond trekking, <b>Reiek</b> is also known for its <b>heritage village</b>, which showcases the traditional Mizo way of life. This cultural site features authentic Mizo-style huts, tribal artifacts, and handcrafted items, offering visitors a chance to experience the rich heritage and traditions of the Mizo people. The village is often the venue for <b>Mizoram’s famous Chapchar Kut Festival</b>, where visitors can witness vibrant Mizo dance performances, folk music, and local delicacies.</p> <p>For adventure lovers, rock climbing and nature walks around <b>Reiek</b> add to the thrill, while those seeking tranquility can enjoy birdwatching and photography in the peaceful surroundings. The area is home to several rare and exotic bird species, making it a great spot for wildlife enthusiasts.</p> <p>Whether you’re looking for an exciting trekking challenge, a cultural experience, or simply a place to relax and soak in Mizoram’s natural beauty, <b>Reiek</b> offers it all. Its unique blend of adventure, culture, and breathtaking scenery makes it one of Mizoram’s top attractions.</p>', 'Go trekking to the peak for a stunning sunrise.', 'Visit during local festivals for a cultural experience.', 'Visit nearby traditional Mizo villages.', 'Visit during winter for pleasant weather.', 'October to March - Best for trekking and outdoor exploration.', '[\"67b14fb6e64b9.jpg\",\"67b14fb6e689d.jpg\",\"67b14fb6e6b61.jpg\"]', 'Aizawl', 'Mizoram', 5000),
(33, 'Hmuifang', 'Hmuifang, a breathtaking hill station in Mizoram, is known for its untouched beauty, rolling meadows, and rich cultural heritage. Located about 50 km from Aizawl, this serene destination sits at an altitude of approximately 1,611 meters, offering a perfect escape for nature lovers and adventure seekers. With its lush greenery, misty hills, and refreshing climate, Hmuifang is an ideal spot for relaxation, trekking, and cultural exploration.\r\n\r\n<p>One of the highlights of <b>Hmuifang</b> is its vast open meadows, which provide stunning panoramic views of the surrounding hills and valleys. These meadows are perfect for camping, picnicking, and photography, making them a popular choice for travelers looking to immerse themselves in nature. The untouched forests of Hmuifang are home to diverse flora and fauna, adding to the charm of this picturesque hill station.</p> <p>Beyond its natural beauty, <b>Hmuifang</b> is deeply connected to Mizoram’s culture and traditions. The annual <b>Thalfavang Kut Festival</b> is held here, celebrating Mizo customs with vibrant dance performances, traditional music, and local delicacies. This event attracts visitors from across the region, offering them a glimpse into the rich heritage of Mizoram.</p> <p>For adventure enthusiasts, <b>Hmuifang</b> offers exciting trekking trails that lead through dense forests and scenic viewpoints. The trails provide breathtaking views of the Mizoram landscape, making them a favorite among trekkers and nature lovers. Wildlife enthusiasts can also explore the region’s forests, which shelter rare bird species and native animals.</p> <p>Whether you\'re looking for a peaceful retreat, an adventure-filled trek, or a chance to experience Mizo culture, <b>Hmuifang</b> is a must-visit destination. Its combination of stunning landscapes, cultural significance, and outdoor activities makes it one of the most enchanting places in Mizoram.</p>', 'Participate in local festivals to experience Mizo culture.', 'Stay in a local homestay to experience Mizo hospitality.', 'Explore the rock cliffs for breathtaking views.', 'Shop for handicrafts from local markets.', 'October to April - Pleasant weather for trekking.	', '[\"67b151106f913.jpg\",\"67b151106fce0.jpg\",\"67b151106ffab.jpg\",\"67b15110702bc.jpg\"]', 'Aizawl', 'Mizoram', 6000),
(34, 'Lengteng Wildlife Sanctuary', 'Lengteng Wildlife Sanctuary, located in the northeastern state of Mizoram, is a paradise for nature lovers and wildlife enthusiasts. This lush green sanctuary is home to a rich diversity of flora and fauna, including several rare and endangered species. Spread across a vast area near the Indo-Myanmar border, Lengteng Wildlife Sanctuary offers a serene escape into the wilderness, making it one of the top eco-tourism destinations in Mizoram.\r\n\r\n<p>One of the main attractions of <b>Lengteng Wildlife Sanctuary</b> is its diverse wildlife, which includes species such as the <b>clouded leopard, Himalayan black bear, goral, and slow loris</b>. The sanctuary is also a birdwatcher’s paradise, with rare species like the <b>Blyth’s tragopan</b>, the state bird of Mizoram, and other exotic birds making it their home. Nature enthusiasts can explore the dense forests, discovering various medicinal plants and unique tree species native to the region.</p> <p>For adventure seekers, <b>Lengteng Wildlife Sanctuary</b> offers excellent trekking opportunities through untouched landscapes. The trails take visitors through thick forests, rolling hills, and breathtaking viewpoints, offering stunning glimpses of Mizoram’s natural beauty. With its serene environment and refreshing mountain air, trekking in this sanctuary is a rejuvenating experience.</p> <p>The sanctuary also holds cultural significance, as it is located close to <b>Lengteng Peak</b>, the second-highest peak in Mizoram. The peak offers panoramic views of the surrounding hills and valleys, making it a must-visit for hikers and photography enthusiasts. The combination of rich biodiversity, scenic landscapes, and adventure activities makes <b>Lengteng Wildlife Sanctuary</b> a perfect getaway for nature lovers.</p> <p>Whether you\'re a wildlife enthusiast looking to spot rare species, an adventurer seeking thrilling trekking trails, or a traveler wanting to experience Mizoram’s unspoiled beauty, <b>Lengteng Wildlife Sanctuary</b> promises an unforgettable experience. Its tranquil atmosphere and breathtaking scenery make it one of the most sought-after destinations for eco-tourism in Mizoram.</p>', 'Go on a jungle safari to spot rare species.', 'Trek through the dense forest trails.', 'Best visited in the early morning for wildlife spotting.', 'Avoid visiting during monsoons due to slippery paths.', 'November to March - Ideal for jungle safaris.	', '[\"67b15382c6d63.jpg\",\"67b15382c7099.jpg\",\"67b15382c7351.jpg\",\"67b15382c75fa.jpg\"]', 'Champhai', 'Mizoram', 6500),
(35, 'Champhai', 'Champhai, a picturesque town in Mizoram, is famously known as the \"Rice Bowl of Mizoram\" due to its vast, lush green rice fields. Nestled near the Indo-Myanmar border, this charming destination offers breathtaking landscapes, rich cultural heritage, and unique experiences for travelers. With its rolling hills, serene environment, and vineyards producing locally made wines, Champhai is a hidden gem waiting to be explored.\r\n\r\n<p>One of the highlights of <b>Champhai</b> is its expansive <b>rice terraces</b>, which not only contribute to the state\'s agricultural economy but also create a stunning visual spectacle. The sight of golden paddy fields stretching across the valley, surrounded by mist-covered hills, makes Champhai an absolute delight for nature lovers and photographers. The region\'s fertile land and favorable climate also support the growth of vineyards, making it a hub for Mizoram\'s local wine production.</p> <p>For history and culture enthusiasts, <b>Champhai</b> has a deep connection to Mizo heritage. The town is home to several ancient relics and landmarks, including the <b>Mangkhaia Lung</b>, a historic stone memorial, and the <b>Fiara Tui</b>, a sacred spring believed to have mythical significance. These sites offer a glimpse into the traditions and legends of the Mizo people, making Champhai a culturally enriching destination.</p> <p>Adventure seekers can explore nearby trekking trails and nature spots such as <b>Rih Dil</b>, a heart-shaped lake located just across the Myanmar border. According to Mizo folklore, this lake is believed to be the passageway to the afterlife, adding a mystical charm to the region. The surrounding hills also provide excellent hiking and birdwatching opportunities for outdoor enthusiasts.</p> <p>Whether you\'re looking for a peaceful retreat amidst nature, a cultural exploration of Mizo traditions, or an offbeat adventure near the <b>Indo-Myanmar border</b>, <b>Champhai</b> offers an unforgettable experience. Its scenic beauty, rich heritage, and agricultural significance make it one of the must-visit destinations in Mizoram.</p>', 'Taste the locally grown grapes and wines.', 'Experience the calm and relaxing ambiance of the town.', 'Try the locally brewed rice beer.', 'Explore nearby scenic viewpoints.', 'October to April - Best for exploring hills and vineyards.	', '[\"67b155ece3f79.jpg\",\"67b155ece440b.jpg\",\"67b155ece4726.jpg\",\"67b155ece49ce.jpg\"]', 'Champhai', 'Mizoram', 6000),
(36, 'Tawi', 'Tawi is a hidden gem in Mizoram, offering tranquil surroundings, lush greenery, and a peaceful retreat away from the bustling city life. This lesser-known destination is perfect for travelers seeking solitude and an authentic connection with nature. With its rolling hills, fresh mountain air, and untouched beauty, Tawi is an ideal spot for those looking to explore Mizoram’s offbeat locations.\r\n\r\n<p>One of the biggest attractions of <b>Tawi</b> is its <b>pristine natural beauty</b>. Surrounded by dense forests and breathtaking landscapes, this destination offers visitors a chance to unwind and rejuvenate in a peaceful setting. Whether you want to take a leisurely walk through the green trails, enjoy a scenic sunrise, or simply relax amidst the untouched wilderness, <b>Tawi</b> provides the perfect backdrop.</p> <p>For nature lovers and adventure seekers, <b>Tawi</b> offers opportunities for <b>trekking and birdwatching</b>. The region is home to a variety of flora and fauna, making it a paradise for wildlife enthusiasts. The untouched landscapes also make it an excellent location for photography, capturing the essence of Mizoram’s raw and unexplored beauty.</p> <p>Unlike mainstream tourist destinations, <b>Tawi</b> retains its local charm and traditional lifestyle. Travelers visiting this serene spot can experience the authentic <b>Mizo culture</b> and hospitality. The nearby villages provide insight into the simple yet beautiful life of the Mizo people, their traditions, and their deep-rooted connection with nature.</p> <p>If you are looking for an <b>offbeat travel experience</b> in Mizoram, <b>Tawi</b> is a must-visit. It is a <b>perfect getaway</b> for those who want to escape the crowds and immerse themselves in the untouched beauty of the Northeast. Whether it’s for relaxation, adventure, or cultural exploration, <b>Tawi</b> offers a unique and memorable experience.</p>', 'Visit during religious festivals for a spiritual experience.', 'Explore the nearby caves and waterfalls.', 'Go on a hike to explore untouched nature.', 'Best for nature lovers seeking peace.', 'October to March - Ideal for temple visits.', '[\"67b1c9c86318f.jpg\",\"67b1c9c863bdd.jpg\",\"67b1c9c863f2c.jpg\"]', 'Serchhip', 'Mizoram', 5500),
(37, 'Aizawl', 'Aizawl, the capital of Mizoram, is a mesmerizing city that perfectly blends modernity with rich cultural heritage. Perched at an altitude of about 1,132 meters, this picturesque hill city offers stunning panoramic views of the surrounding valleys and lush green hills. Known for its vibrant culture, bustling markets, and serene landscapes, Aizawl is an ideal destination for travelers looking to experience the essence of Mizoram.\r\n\r\n<p>One of the major highlights of <b>Aizawl</b> is its unique cultural heritage. The city is home to several traditional Mizo festivals, music, and dance forms that showcase the lively spirit of the locals. Visitors can explore <b>Solomon\'s Temple</b>, a magnificent architectural structure, and <b>Mizoram State Museum</b>, which offers a deep insight into the state\'s rich history, traditional costumes, and artifacts.</p> <p>For nature lovers, <b>Durtlang Hills</b> provide a perfect spot to enjoy breathtaking views of Aizawl from a higher altitude. The <b>Reiek Tourist Village</b>, located nearby, offers an authentic experience of Mizo lifestyle while providing spectacular views of the surrounding landscapes. Adventure seekers can also embark on trekking trails and enjoy the fresh mountain air.</p> <p>Shopping in <b>Aizawl’s local markets</b>, like <b>Bara Bazar</b>, is a must-do experience. These bustling streets are filled with colorful stalls selling traditional handwoven textiles, bamboo handicrafts, and locally made accessories. Food enthusiasts can savor authentic <b>Mizo cuisine</b>, including delicacies like <b>Bai</b> (vegetable stew), <b>Vawksa Rep</b> (smoked pork), and <b>Bamboo Shoot Curry</b>.</p> <p>Whether you are a nature lover, a cultural explorer, or simply looking for a peaceful retreat, <b>Aizawl</b> offers something for everyone. Its stunning landscapes, welcoming locals, and unique traditions make it one of the most captivating destinations in Northeast India.</p>', 'Explore the Mizoram State Museum to learn about local culture.', 'Try Mizo dishes like Bamboo Shoot Curry.', 'Visit Solomon’s Temple for a peaceful retreat.', 'Stay at a homestay to experience Mizo hospitality.', 'October to March - Cool and pleasant weather for travel.	', '[\"67b1cb0a8b891.jpg\",\"67b1cb0a8bc33.jpg\",\"67b1cb0a8bea0.jpg\",\"67b1cb0a8c1ee.jpg\",\"67b1cb0a8c42c.jpg\",\"67b1cb0a8c63c.jpg\",\"67b1cb0a8c85b.png\",\"67b1cb0a8ca6b.jpg\",\"67b1cb0a8cc94.jpg\",\"67b1cb0a8ce8f.jpg\",\"67b1cb0a8d080.png\"]', 'Aizawl', 'Mizoram', 5500),
(38, 'Laitlum Canyons', 'Laitlum Canyons, which translates to \"End of Hills,\" is one of the most stunning and lesser-explored destinations in Meghalaya. Located just a short drive from Shillong, this mesmerizing spot offers panoramic views of deep valleys, rolling hills, and mist-covered mountains. The untouched beauty of Laitlum makes it an ideal place for nature lovers, photographers, and adventure seekers looking for a peaceful retreat away from the city\'s hustle.\r\n\r\n<p>One of the biggest attractions of <b>Laitlum Canyons</b> is its breathtaking sunrise and sunset views. The sight of golden hues spreading over the vast green landscapes is a surreal experience. The area is surrounded by lush greenery and deep gorges, making it a haven for photographers and nature enthusiasts.</p> <p>For trekking enthusiasts, <b>Laitlum’s rugged trails</b> provide a thrilling experience. The trek down the canyon leads to the remote village of Rasong, where visitors can witness the traditional lifestyle of the Khasi community. The trek is moderately challenging but rewarding, offering glimpses of unspoiled nature and fresh mountain air.</p> <p>The calm and serene atmosphere of <b>Laitlum Canyons</b> makes it an ideal destination for those looking to unwind and enjoy Meghalaya’s pristine beauty. The absence of commercial crowds allows travelers to soak in the peaceful surroundings, making it a perfect escape for solitude seekers.</p> <p>Whether you are an adventurer, a photographer, or someone seeking tranquility amidst nature, <b>Laitlum Canyons</b> is a must-visit destination in Meghalaya. Its mesmerizing landscapes, thrilling trails, and peaceful ambiance make it one of the most captivating spots in the Northeast.</p>', 'Enjoy a scenic trek for breathtaking landscapes.', 'Best time to visit is during sunrise or sunset.', 'Best visited with a local guide for safety.', 'Visit after monsoons for lush greenery.', 'October to May - Best time for trekking and sightseeing.	', '[\"67b1cd4c8900a.jpg\",\"67b1cd4c89498.jpg\",\"67b1cd4c8979f.jpg\",\"67b1cd4c89bd4.jpg\",\"67b1cd4c89fe8.jpg\",\"67b1cd4c8a453.jpg\",\"67b1cd4c8a816.jpg\"]', 'Shillong', 'Meghalaya', 5500);

-- --------------------------------------------------------

--
-- Table structure for table `hillstation`
--

CREATE TABLE `hillstation` (
  `hill_station_id` int(5) NOT NULL,
  `dest_name` varchar(150) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `tip1` varchar(150) NOT NULL,
  `tip2` varchar(150) NOT NULL,
  `tip3` varchar(150) NOT NULL,
  `tip4` varchar(150) NOT NULL,
  `best_time` varchar(150) NOT NULL,
  `fileImg` varchar(500) NOT NULL,
  `city` varchar(50) NOT NULL,
  `states` varchar(50) NOT NULL,
  `budget` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `mountain`
--

CREATE TABLE `mountain` (
  `mountain_id` int(5) NOT NULL,
  `dest_name` varchar(150) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `tip1` varchar(150) NOT NULL,
  `tip2` varchar(150) NOT NULL,
  `tip3` varchar(150) NOT NULL,
  `tip4` varchar(150) NOT NULL,
  `best_time` varchar(150) NOT NULL,
  `fileImg` varchar(500) NOT NULL,
  `city` varchar(50) NOT NULL,
  `states` varchar(50) NOT NULL,
  `budget` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `movie`
--

CREATE TABLE `movie` (
  `movie_id` int(5) NOT NULL,
  `movie_title` varchar(150) NOT NULL,
  `description` varchar(500) NOT NULL,
  `dest_1` varchar(150) NOT NULL,
  `description1` varchar(500) NOT NULL,
  `city1` varchar(50) NOT NULL,
  `states1` varchar(50) NOT NULL,
  `dest_2` varchar(150) NOT NULL,
  `description2` varchar(500) NOT NULL,
  `city2` varchar(50) NOT NULL,
  `states2` varchar(50) NOT NULL,
  `dest_3` varchar(150) NOT NULL,
  `description3` varchar(500) NOT NULL,
  `city3` varchar(50) NOT NULL,
  `states3` varchar(50) NOT NULL,
  `dest_4` varchar(150) NOT NULL,
  `description4` varchar(500) NOT NULL,
  `city4` varchar(50) NOT NULL,
  `states4` varchar(50) NOT NULL,
  `budget` varchar(10) NOT NULL,
  `fileImg` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `movie`
--

INSERT INTO `movie` (`movie_id`, `movie_title`, `description`, `dest_1`, `description1`, `city1`, `states1`, `dest_2`, `description2`, `city2`, `states2`, `dest_3`, `description3`, `city3`, `states3`, `dest_4`, `description4`, `city4`, `states4`, `budget`, `fileImg`) VALUES
(1, 'Go  Goa Gone', 'asdsdsads', 'goa 1', 'sasad', 'panji', 'goa', 'goa2', 'sasda', 'panji', 'goa', 'goa3', 'assad', 'panji', 'goa', 'goa 4', 'asdasad', 'panji', 'goa', '1500', '[\"6787de30be948.jpeg\",\"6787de30beb99.jpg\",\"6787de30becf5.jpeg\"]');

-- --------------------------------------------------------

--
-- Table structure for table `palace`
--

CREATE TABLE `palace` (
  `palace_id` int(5) NOT NULL,
  `dest_name` varchar(150) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `tip1` varchar(150) NOT NULL,
  `tip2` varchar(150) NOT NULL,
  `tip3` varchar(150) NOT NULL,
  `tip4` varchar(150) NOT NULL,
  `best_time` varchar(150) NOT NULL,
  `fileImg` varchar(500) NOT NULL,
  `city` varchar(50) NOT NULL,
  `states` varchar(50) NOT NULL,
  `budget` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `user_detail`
--

CREATE TABLE `user_detail` (
  `user_id` int(5) NOT NULL,
  `uname` varchar(200) NOT NULL,
  `email` varchar(250) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user_detail`
--

INSERT INTO `user_detail` (`user_id`, `uname`, `email`, `password`) VALUES
(1, 'pratham2sharma', 'sharmapratham1208@gmail.com', '$2y$10$.YdNBU85EoGTyMx0tLzJguOcjoIZ5wm1y8xkDI9mLs9UeQR9uHv4a');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `beach`
--
ALTER TABLE `beach`
  ADD PRIMARY KEY (`beach_id`);

--
-- Indexes for table `blog`
--
ALTER TABLE `blog`
  ADD PRIMARY KEY (`blog_id`);

--
-- Indexes for table `destination`
--
ALTER TABLE `destination`
  ADD PRIMARY KEY (`place_id`);

--
-- Indexes for table `hillstation`
--
ALTER TABLE `hillstation`
  ADD PRIMARY KEY (`hill_station_id`);

--
-- Indexes for table `mountain`
--
ALTER TABLE `mountain`
  ADD PRIMARY KEY (`mountain_id`);

--
-- Indexes for table `movie`
--
ALTER TABLE `movie`
  ADD PRIMARY KEY (`movie_id`);

--
-- Indexes for table `palace`
--
ALTER TABLE `palace`
  ADD PRIMARY KEY (`palace_id`);

--
-- Indexes for table `user_detail`
--
ALTER TABLE `user_detail`
  ADD PRIMARY KEY (`user_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `beach`
--
ALTER TABLE `beach`
  MODIFY `beach_id` int(5) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `blog`
--
ALTER TABLE `blog`
  MODIFY `blog_id` int(5) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `destination`
--
ALTER TABLE `destination`
  MODIFY `place_id` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;

--
-- AUTO_INCREMENT for table `hillstation`
--
ALTER TABLE `hillstation`
  MODIFY `hill_station_id` int(5) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `mountain`
--
ALTER TABLE `mountain`
  MODIFY `mountain_id` int(5) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `movie`
--
ALTER TABLE `movie`
  MODIFY `movie_id` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `palace`
--
ALTER TABLE `palace`
  MODIFY `palace_id` int(5) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `user_detail`
--
ALTER TABLE `user_detail`
  MODIFY `user_id` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
